[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    beegee-tokyo/DHT sensor library for ESPx@^1.19
    tzapu/WiFiManager@^2.0.17
